version: 2
jobs:
  deploy:
    machine:
      enabled: true
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS: "/etc/google/auth/application_default_credentials.json"
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd koieneres-backend && git reset --hard HEAD && git pull && /snap/bin/docker-compose up -d --no-deps --build api"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
