# Generated by Django 2.1.5 on 2019-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='article_number',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
