# Generated by Django 2.1.5 on 2019-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20190129_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='member_price',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='non_member_price',
            field=models.FloatField(default=80),
        ),
    ]
