# Generated by Django 2.1.5 on 2019-01-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20190118_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='to_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='membership_number',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='should_pay',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
