# Generated by Django 2.1.5 on 2019-01-29 13:21

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20190129_1414'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='reservation_date_737521_brin'),
        ),
    ]
