# Generated by Django 2.1.5 on 2019-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20190129_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmetadata',
            options={'ordering': ('-created_at', )},
        ),
        migrations.AddField(
            model_name='reservationmetadata',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
