# Generated by Django 2.1.5 on 2019-02-28 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0007_auto_20190214_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinClosing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Cabin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
