# Generated by Django 2.1.5 on 2019-03-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_cabinclosing_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPeriod',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('reservation_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
