# Generated by Django 2.2.5 on 2019-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_cabin_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinclosing',
            name='avalanche_warning',
            field=models.BooleanField(default=False),
        ),
    ]
