# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('from_date', 'to_date')},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='fromDate',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='toDate',
            new_name='to_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
